 [#ftl]
 [@b.grid items=squades var="squad"]
   [@b.row]
     [@b.boxcol/]
     [@b.col property="grade" title="std.state.grade"/]
     [@b.col property="name" title="attr.name"]
       [@b.a href="#" onclick="if(typeof adminClassIdAction!='undefined')adminClassIdAction(${squad.id})" target="_blank"][@i18nName squad/][/@]
     [/@]
     [@b.col property="stdType.name" title="entity.studentType"/]
     [@b.col property="department.name" title="entity.department"/]
     [@b.col property="major.name" title="entity.major"/]
     [@b.col property="direction.name" title="entity.direction"/]
   [/@]
 [/@]
