[#ftl/]
 [@b.grid items=students var="std"]
     [@b.row]
         [@b.boxcol/]
         [@b.col title="attr.stdNo" property="code" width="12%"]${std.code}[/@]
         [@b.col title="attr.personName" property="user.name" width="10%"][@b.a href="javascript:if(typeof stdIdAction !='undefined') stdIdAction('${std.id}');" title="${stdNameTitle?if_exists}"][/@]${std.name}[/@]
         [@b.col title="entity.gender" property="person.gender" width="5%"][@i18nName std.person.gender?if_exists/][/@]
         [@b.col title="std.state.grade" property="state.grade.code" width="5%"/]
         [@b.col title="培养层次" property="level.name" width="10%"][@i18nName std.level?if_exists/][/@]
         [@b.col title="院系" property="state.department.name" width="15%"][@i18nName std.state.department?if_exists/][/@]
         [@b.col title="entity.major" property="state.major.name" width="20%"][@i18nName std.major?if_exists/] [@i18nName std.state.direction?if_exists/][/@]
         [@b.col title="entity.class" property ="state.squad.name" width="20%"][@i18nName std.state.squad!/][/@]
     [/@]
 [/@]
