[#ftl]
[@b.head/]
[@b.form name="checkFeeTypeForm" action="!search"]
  [@b.grid id="checkFeeTypeTable" items=checkFeeTypes var="checkFeeType" filterable="true"]
    [@b.gridbar title="验证条件列表"]
      bar.addItem("${b.text("action.new")}",action.add());
      bar.addItem("${b.text("action.edit")}",action.edit());
      bar.addItem("${b.text("action.delete")}",action.remove());
    [/@]
    [@b.gridfilter property="feeType"]
      [@b.select theme="html" name="checkFeeType.feeType" items=feeTypes value=Parameters['checkFeeType.feeType.id'] empty="..." style="width:100%" onchange="jQuery('#checkFeeTypeTable_filter_submit').click();"/]
    [/@]
    [@b.row]
      [@b.boxcol/]
      [@b.col title="费用类型" property="feeType"]
        [#if checkFeeType.feeType??]${checkFeeType.feeType.name}[/#if]
      [/@]
    [/@]
  [/@]
[/@]
[@b.foot/]
